name: Continues Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Node-Docker-EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/souqMuscatBackend
          git pull origin main
          docker stop souqMuscatBackend
          docker rm souqMuscatBackend
          docker rmi souq:production
          docker build . -t souq:production
          docker run -dt --restart unless-stopped --name souqMuscatBackend -p 8081:3000 -v /home/ubuntu/souqMuscatBackend:/home/node/app souq:production
          docker volume prune
