name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to node_server
      uses: appleboy/ssh-action@master
      with:
        host: 97.74.86.93
        username: deployer
        key: ${{ secrets.SSH_KEY }}
        port: 3222
        script: |
          cd souqMuscatBackend
          git pull origin main
          docker build -t souqMuscat .
          docker run --name souqMuscatBackend -d -p 8085:80 souqMuscat:latest
          docker volume prune
