name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to node_server
      uses: appleboy/ssh-action@master
      with:
        host: 97.74.86.93
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd souqMuscatBackend
          git pull origin main
          docker build -t souqmuscat .
          docker run --name souqMuscatBackend -d -p 8085:80 souqmuscat:latest
          docker volume prune
